version: 2
endpoint: http://35.225.62.128:8080
admin_secret: myadminsecretkey
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
  # ACTION_BASE_ENDPOINT: ${ACTION_BASE_ENDPOINT}
