name: .NET Core Build with Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    # use ubuntu for more build minutes
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./server
    # # use release mode for all steps
    env:
      config: "Release"
      # dotnet won't restore without this
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.103

      - name: Install dependencies docker containers
        run: docker-compose up -d

      # restore dependencies
      - name: Install dependencies src
        run: dotnet restore
        working-directory: ./server/src
      - name: Install dependencies src.test
        run: dotnet restore
        working-directory: ./server/src.test

        # build project
      - name: Build src
        run: dotnet build --configuration $config --no-restore
        working-directory: ./server/src
      - name: Build src.test
        run: dotnet build --configuration $config --no-restore
        working-directory: ./server/src.test

      # set pr number, if it's a pr build
      - name: set pr build number
        id: PRNUMBER
        if: ${{ github.event_name == 'pull_request' }}
        uses: kkak10/pr-number-action@v1.3

      # run tests with built project
      - name: Test PR
        run: dotnet test --no-restore --no-build --configuration $config
        # run: dotnet test
        working-directory: ./server/src.test

      - name: Tests âœ…
        if: ${{ success() }}
        run: |
          curl --request POST           --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}           --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'           --header 'content-type: application/json'           --data '{
            "context": "tests",
            "state": "success",
            "description": "Tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
      - name: Tests ðŸš¨
        if: ${{ failure() }}
        run: |
          curl --request POST           --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}           --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'           --header 'content-type: application/json'           --data '{
            "context": "tests",
            "state": "failure",
            "description": "Tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
